name: TownyElections
version: '%version%'
main: site.remlit.townyelections.TownyElections
api-version: '1.20'
load: POSTWORLD
authors: [ blueb ]
loader: site.remlit.townyelections.TownyElectionsPluginLoader

depend:
  - Towny
softdepend:
  - PlaceholderAPI
